### ISSUE TITLE
ModuleNotFoundError: No module named 'markdownxcore'

### ISSUE THREAD

**Issue by Sidon** [neutronX/django-markdownx#115]
Hi,
When I try to run my app I get this error: ModuleNotFoundError: No module named 'markdownxcore', what is wrong?

Python: 3.6
Django: 1.11.12

```
$ pip show django-markdownx
Name: django-markdownx
Version: 2.0.22
```

**settings.py:**
```
INSTALLED_APPS = [
   ...
    'markdownx'
    'core',
]
```
**views.py**
```
from markdownx.utils import markdownify
...
class HomeView(TemplateView):
    template_name = 'core/home.html'
    context_object_name = 'markdown'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        with open('doc/home.txt', 'r') as f:
            data = f.readlines()
        context['markdwon'] = markdownify(data)
        return context
```
**Errors**

```
/manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f875ec82730>
Traceback (most recent call last):
  File "/home/sidon/miniconda3/envs/olist/lib/python3.6/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/sidon/miniconda3/envs/olist/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/sidon/miniconda3/envs/olist/lib/python3.6/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/home/sidon/miniconda3/envs/olist/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/sidon/miniconda3/envs/olist/lib/python3.6/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/sidon/miniconda3/envs/olist/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/sidon/miniconda3/envs/olist/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/sidon/miniconda3/envs/olist/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/home/sidon/miniconda3/envs/olist/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'markdownxcore'
```

**Comment by adi-** [comment]
INSTALLED_APPS = [
   ...
    'markdownx'
    'core',
]

Cant see a comma after markdownx

**Comment by Sidon** [comment]
Yes....
Thank you, that is the mistake.

**Comment by Sidon** [comment]
Thanks!
