### ISSUE TITLE
Trying to check jpeg with "has_javascript"

### ISSUE THREAD

**Issue by lolorama** [neutronX/django-markdownx#61]
pip installation of the latest markdownx package raises exception below when I try to upload an image.

```
Internal Server Error: /markdownx/upload/
Traceback (most recent call last):
  File "/Users/ksanderer/.pyenv/versions/django_boiler/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/ksanderer/.pyenv/versions/django_boiler/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/ksanderer/.pyenv/versions/django_boiler/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ksanderer/.pyenv/versions/django_boiler/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ksanderer/.pyenv/versions/django_boiler/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ksanderer/.pyenv/versions/django_boiler/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ksanderer/.pyenv/versions/django_boiler/lib/python3.5/site-packages/django/views/generic/edit.py", line 182, in post
    if form.is_valid():
  File "/Users/ksanderer/.pyenv/versions/django_boiler/lib/python3.5/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/Users/ksanderer/.pyenv/versions/django_boiler/lib/python3.5/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/Users/ksanderer/.pyenv/versions/django_boiler/lib/python3.5/site-packages/django/forms/forms.py", line 385, in full_clean
    self._clean_form()
  File "/Users/ksanderer/.pyenv/versions/django_boiler/lib/python3.5/site-packages/django/forms/forms.py", line 412, in _clean_form
    cleaned_data = self.clean()
  File "/Users/ksanderer/.pyenv/versions/django_boiler/lib/python3.5/site-packages/markdownx/forms.py", line 183, in clean
    and has_javascript(upload.read())):
  File "/Users/ksanderer/.pyenv/versions/django_boiler/lib/python3.5/site-packages/markdownx/utils.py", line 131, in has_javascript
    flags=IGNORECASE | MULTILINE
  File "/Users/ksanderer/.pyenv/versions/3.5.1/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```

You can see that "has_javascript" executes in this piece of code:

```
# markdownx/forms.py (line: 183)
        if content_type not in MARKDOWNX_UPLOAD_CONTENT_TYPES:
            raise MarkdownxImageUploadError.unsupported_format()

        elif file_size > MARKDOWNX_UPLOAD_MAX_SIZE:
            raise MarkdownxImageUploadError.invalid_size(
                current=file_size,
                expected=MARKDOWNX_UPLOAD_MAX_SIZE
            )

        elif (content_type.lower() != self._SVG_TYPE
              and MARKDOWNX_SVG_JAVASCRIPT_PROTECTION
              and has_javascript(upload.read())):
```

When we trying to upload JPEG file the last "elif" always will fire with "has_javascript" check.

Shouldn't it be `content_type.lower() == self._SVG_TYPE` ?

**Comment by xenatisch** [comment]
oh really? I'll deal with that right away. Thanks for pointing it out.

**Comment by lolorama** [comment]
Thanks! Yeah.. It happens sometimes :)
